USE [TWR_DW_STAGE]
GO

CREATE TABLE [wpc].[ACCOUNTING_PERIOD_EDW](
	[ACCOUNTING_PERIOD_CD] [numeric](6, 0) NOT NULL,
	[ACCOUNTING_PERIOD_MONTH] [numeric](2, 0) NOT NULL,
	[ACCOUNTING_PERIOD_YEAR] [numeric](4, 0) NOT NULL,
	[ACCOUNTING_PERIOD_SRC_CD] [int] NOT NULL,
	[ACCOUNTING_PERIOD_START_DT] [date] NOT NULL,
	[ACCOUNTING_PERIOD_END_DT] [date] NOT NULL,
	[LAST_USER_ID] [varchar](100) NOT NULL,
	[LOAD_TS] [datetime] NOT NULL,
	[ACCOUNTING_PERIOD_KEY] [bigint] NOT NULL
) ON [PRIMARY]

GO
