USE [TWR_DW_STAGE]
GO

CREATE TABLE [wpc].[COVERAGE](
    [POLICY_VERSION_ID] [varchar](30) NOT NULL,
	[POLICY_TERM_KEY] [bigint] NULL,
    [COVERAGE_KEY] [bigint] NOT NULL,
    [RISK_KEY] [bigint] NULL,
    [COVERAGE_LEVEL_CD] [varchar](1) NULL,
    [COV_EFF_DT] [datetime] NULL,
    [COV_EXP_DT] [datetime] NULL,
    [STATE_CD] [varchar](2) NULL,
    [LOB_CD] [varchar](2) NULL,
    [ASLOB_CD] [varchar](4) NULL,
    [SUBLINE_CD] [varchar](4) NULL,
    [COVERAGE_CD] [varchar](100) NULL,
    [PREMIUM_AMT] [money] NULL,
    [AGGREGATE_DED_AMT] [money] NULL,
    [LOAD_TS] [datetime] NOT NULL,
    [FULLY_EARNED_IND] [varchar](1) NULL,
    [UNIT_NUMBER] [int] NULL,
	[MULTI_CAR_DISCOUNT_IND] varchar(1) NULL,
	[WPC_COV_KEY] [int] NULL,
	[WPC_PROPERTY_KEY] [int] NULL,
	[WPC_UNIT_KEY] [int] NULL,
	[USER_LINE] varchar(2) NULL
) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [INDX_PCOV1] ON [wpc].[COVERAGE] 
(
	[POLICY_TERM_KEY] ASC,
	[ASLOB_CD] ASC,
	[WPC_COV_KEY] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [WPC_COV_TSUM] ON [wpc].[COVERAGE] 
(
	[POLICY_TERM_KEY] ASC,
	[COVERAGE_LEVEL_CD] ASC,
	[STATE_CD] ASC,
	[COVERAGE_CD] ASC,
	[UNIT_NUMBER] ASC
)
INCLUDE ( [ASLOB_CD],
[WPC_COV_KEY]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO
