USE [TWR_DW_STAGE]
GO

CREATE TABLE [wpc].[POLICY_TERM](
[POLICY_VERSION_ID] [varchar](30) NOT NULL,
[POLICY_TERM_KEY] [bigint] NULL,
[VALID_FROM_DT] [datetime] NULL,
[VALID_TO_DT] [datetime] NULL,
[VERSION_SEQ] int NULL,
[CURRENT_IND] [varchar](1) NULL,
[COMPANY_CD] [varchar](5) NOT NULL,
[POLICY_NO] [varchar](50) NULL,  
[POLICY_EFF_DT] [datetime] NULL,
[POLICY_EXP_DT] [datetime] NULL,    
[ORIGINAL_INCEPTION_DT] [datetime] NULL,
[CANCEL_REINSTATE_CD] [varchar](1) NULL,
[CANCEL_EFF_DT] [datetime] NULL,
[CANCEL_METHOD_CD] [varchar](2) NULL,
[PRODUCER_ID] [varchar](50) NULL,
[SUBPRODUCER_CD] [varchar](50) NULL,
[BRANCH_CD] [varchar](4) NULL,
[PROGRAM_CD] [varchar](6) NULL,    
[POLICY_TYPE_CD] [varchar](2) NULL,
[PERSONAL_LINES_IND] [varchar](1) NULL,
[BILLING_PLAN_CD] [varchar](10) NULL,
[ISO_TYPE_OF_POLICY_CD] [varchar](2) NULL,
[CUSTOMER_ID] [varchar](50) NULL,
[INSURED_NAME] [varchar](255) NULL,
[COMMISSION_RATE] [numeric](18, 8) NULL,
[PREMIUM_AMT] [money] NULL,
[SRC_PREMIUM_AMT] [money] NULL,
[PREM_ANNUALIZED_AMT] [money] NULL,
[PRIMARY_RATING_STATE_CD] [varchar](2) NULL,
[GOVERNING_CLASS_CD] [varchar](10) NULL,
[PRIOR_POLICY_NO] [varchar](50) NULL,
[NEW_RENEWAL_IND] [varchar](1) NULL,
[SUBJECT_TO_AUDIT_IND] [varchar](1) NULL,
[AUDIT_TYPE] [varchar](1) NULL,
[UNDERWRITER_NAME] [varchar](100) NULL,
[POLICY_INCEPTION_YEAR] [numeric](2, 0) NULL,
[INDIVIDUAL_BUSINESS_IND] varchar(1) NULL,
[POLICY_MOD_NO] [int] NULL,
[COMMERCIAL_PERSONAL_IND] [varchar](1) NULL,
[CANCELLATION_DT] [date] NULL,
[POLICY_SUBMISSION_STATUS_CD] [varchar](20) NULL,
[PACKAGE_IND] [varchar](1) NULL,
[LIABILITY_ONLY_IND] [varchar](1) NULL,
[CANCEL_REASON_CD] [varchar](150) NULL,
[SRC_MODIFIED_TS] [datetime] NULL,
[NON_RENEWABLE_IND] [varchar](2) NULL,
[ORIGINAL_ISSUE_DT] [date] NULL,
[WPC_POLICY_KEY] [int] NULL,
[LOAD_TS] [datetime] NOT NULL
) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [INDX_PTERM_WPC_KEY] ON [wpc].[POLICY_TERM] 
(
	[POLICY_TERM_KEY] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [INDX_WPC_PTER] ON [wpc].[POLICY_TERM] 
(
	[POLICY_NO] ASC,
	[POLICY_EFF_DT] ASC,
	[VERSION_SEQ] ASC
)
INCLUDE ( [POLICY_TERM_KEY]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

GO
